version: "3"
services:
    database:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: LKJie7t65whb
            MYSQL_DATABASE: ctf_platform
            MYSQL_USER: ctfuser
            MYSQL_PASSWORD: ctfuser_LKJie7t65whb
            LANG: C.UTF-8
        ports:
            - "3306:3306"
        volumes:
            - ./data/:/var/lib/mysql
            - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    channels:
        image: redis
        ports:
            - "6379:6379"
    api:
        restart: always
        build:
            context: .
            args:
                database_url: "mysql://ctfuser:ctfuser_LKJie7t65whb@database:3306/ctf_platform"
                redis_host: "channels"
        ports:
            - "8001:8001"
        command: sh -c "python3 manage.py migrate &&
                        gunicorn -b 0.0.0.0:8001 ctf_platform.wsgi:application"
        volumes:
            - ./media:/code/media/
    websocket:
        build:
            context: .
            args:
                database_url: "mysql://ctfuser:ctfuser_LKJie7t65whb@database:3306/ctf_platform"
                redis_host: "channels" 
        ports:
            - "9001:9001"
        command: daphne -b 0.0.0.0 -p 9001 ctf_platform.asgi:application
